export const WORK_ORDER_STATUSES = [
  'DRAFT', 'RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'IN_PROGRESS',
  'QUALITY_CHECK', 'READY_FOR_DELIVERY', 'CLOSED', 'ON_HOLD', 'CANCELLED',
] as const;

export type WorkOrderStatus = (typeof WORK_ORDER_STATUSES)[number];

export const ALLOWED_TRANSITIONS: Record<WorkOrderStatus, WorkOrderStatus[]> = {
  DRAFT: ['RECEIVED', 'CANCELLED'],
  RECEIVED: ['DIAGNOSING', 'ON_HOLD', 'CANCELLED'],
  DIAGNOSING: ['WAITING_APPROVAL', 'IN_PROGRESS', 'ON_HOLD'],
  WAITING_APPROVAL: ['APPROVED', 'IN_PROGRESS', 'ON_HOLD', 'CANCELLED'],
  APPROVED: ['IN_PROGRESS', 'ON_HOLD'],
  IN_PROGRESS: ['READY_FOR_DELIVERY', 'QUALITY_CHECK', 'ON_HOLD'],
  QUALITY_CHECK: ['READY_FOR_DELIVERY', 'IN_PROGRESS'],
  READY_FOR_DELIVERY: ['CLOSED', 'IN_PROGRESS'],
  CLOSED: [],
  ON_HOLD: ['DIAGNOSING', 'IN_PROGRESS', 'CANCELLED'],
  CANCELLED: [],
};
